remove cm_find_package macro declaration across all modules
NilFoundation/crypto3 pull request #233
Opened 2024-05-28 08:19 UTC by AndreyMlashkin

2024-05-28 09:15 UTC, x-mass commented
Comment from ancestor: 
Since the changes affect CMake, I have overall comments on this.

Take a look at [this commit](https://github.com/NilFoundation/crypto3-algebra/commit/f4a68ed9de9bc47eadf165be17c7172e33edc11b). You should note:

    ${Boost_LIBRARIES} -> Boost::lib_name
    Removal of if(ENABLE_JUNIT_TEST_OUTPUT). We now have flags to mimic such behavior, they are in flake.nix
    Removal of get_target_property(target_type Boost::unit_test_framework TYPE). It automatically substitutes these flags
    Removal of if(NOT Boost_FOUND AND NOT CMAKE_CROSSCOMPILING). It's just nonsensical part.

In addition, you can call find_package(Boost REQUIRED COMPONENTS ...) once at the root of crypto3 and remove find_package from the submodules entirely.

2024-05-28 21:16 UTC, x-mass requested changes

2024-05-28 21:16 UTC, x-mass commented on CMakeLists.txt
> -option(USE_STATIC_BOOST "Use static libraries for Boost" FALSE)
Why did you remove it? Could you show me the part where `Boost_USE_STATIC_LIBS` is set? 
Have you tried to configure it with different linking and check if there are proper flags passed to compiler? (You can do it with `make VERBOSE=1 target_name`)

2024-05-28 21:16 UTC, x-mass commented on libs/algebra/example/CMakeLists.txt
> +set_target_properties(algebra_${name}_example PROPERTIES CXX_STANDARD 14)
Offset

2024-05-28 21:16 UTC, x-mass commented on libs/math/CMakeLists.txt
>  list(APPEND ${CURRENT_PROJECT_NAME}_PUBLIC_HEADERS)
Remove such useless lists as well. Check other files, it is not the only place with this issue

2024-05-28 21:16 UTC, x-mass commented on libs/math/test/benchmarks/CMakeLists.txt
>      ${CMAKE_WORKSPACE_NAME}::multiprecision
No need to link libs one more time, if already linked with `${CMAKE_WORKSPACE_NAME}_${CURRENT_PROJECT_NAME}`. Check for other modules as well

2024-05-28 21:16 UTC, x-mass commented on libs/algebra/test/bench_test/CMakeLists.txt
>      endif()
From comment: _Removal of get_target_property(target_type Boost::unit_test_framework TYPE). It automatically substitutes these flags_.
Not _replace with if(NOT ${Boost_USE_STATIC_LIB})_.

It means you have to **remove** it. Flags are already handled by Boost cmake inner logic. It sets `BOOST_UNIT_TEST_FRAMEWORK_DYN_LINK`, then this sets `BOOST_TEST_DYN_LINK` [here](https://github.com/boostorg/test/blob/ee2ec56b0938163da4782d062a88a05fdab912c6/include/boost/test/detail/config.hpp#L96-L101)

2024-05-28 22:49 UTC, x-mass commented
I think, some commits are tiny and should be squased together. Say, [dd19c43](https://github.com/NilFoundation/crypto3/pull/233/commits/dd19c4388f5c54a06053fdde259b5b58e09a326d) and [a07e650](https://github.com/NilFoundation/crypto3/pull/233/commits/a07e65038c198d58b1748d91d887951d77e42a14) are exactly about the same issue. Mb squash all of these? The more commits we have, the more flooded history we get

2024-05-29 08:47 UTC, AndreyMlashkin commented on libs/math/test/benchmarks/CMakeLists.txt
>      ${CMAKE_WORKSPACE_NAME}::multiprecision
It's a bench test, here it's a bit special, it's included not with the cm_add_tests macro, but like this:

if(ENABLE_BENCHMARKS)
    add_subdirectory(benchmarks)
endif()

2024-05-29 08:48 UTC, AndreyMlashkin commented on libs/math/test/benchmarks/CMakeLists.txt
>      ${CMAKE_WORKSPACE_NAME}::multiprecision
I will re-work bench tests more later. I will create a separate folder on the root level. But as a part of a separate topic

2024-05-29 09:13 UTC, AndreyMlashkin commented on libs/algebra/test/bench_test/CMakeLists.txt
>      endif()
done

2024-05-29 09:14 UTC, AndreyMlashkin commented on libs/math/CMakeLists.txt
>  list(APPEND ${CURRENT_PROJECT_NAME}_PUBLIC_HEADERS)
Can we do it in a follow-up? I need these changes for fixing blueprint

2024-05-29 09:14 UTC, AndreyMlashkin commented on libs/algebra/example/CMakeLists.txt
> +set_target_properties(algebra_${name}_example PROPERTIES CXX_STANDARD 14)
done

2024-05-29 09:15 UTC, AndreyMlashkin commented on CMakeLists.txt
> -option(USE_STATIC_BOOST "Use static libraries for Boost" FALSE)
I have re-introduced it as Boost_USE_STATIC_LIBS to avoid one more flag declaration

2024-05-29 09:27 UTC, x-mass commented on CMakeLists.txt
> -option(USE_STATIC_BOOST "Use static libraries for Boost" FALSE)
Ok. I missed that -DSomeOpt=1 is the same as set(SomeOpt 1)

2024-05-29 09:50 UTC, AndreyMlashkin commented on CMakeLists.txt
> -option(USE_STATIC_BOOST "Use static libraries for Boost" FALSE)
Should I change something on this point?

2024-05-29 09:51 UTC, x-mass commented on CMakeLists.txt
> -option(USE_STATIC_BOOST "Use static libraries for Boost" FALSE)
Make an option with Boost_USE_STATIC_LIBS, so it will be obvious we have this option

2024-05-29 09:51 UTC, x-mass commented on CMakeLists.txt
> +option(ENABLE_TESTS "Enable tests" TRUE) # used by CMTest module
Have you checked it? Try to remove CMAKE_ENABLE_TESTS and add ENABLE_TESTS to nix

2024-05-29 10:02 UTC, x-mass approved these changes

2024-05-29 12:07 UTC, merged